# Generated by Django 5.2.8 on 2025-11-30 14:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business', models.BooleanField(default=False)),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('send_locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('receive_locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trans_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit from external provider (MPESA C2B)'), ('WITHDRAWAL', 'Withdrawal to external provider (B2C)')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sender_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('external_provider', models.CharField(blank=True, max_length=32, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('reconciled', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, help_text='id for product purchased', max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('RELEASE_REQUESTED', 'Release Requested'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('REVERSED', 'Reversed')], default='HELD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='wallet.paymenttransaction')),
                ('payer_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_paid_allocations', to='wallet.wallet')),
                ('receiver_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_received_allocations', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('DEPOSIT', 'External deposit'), ('ESCROW_HOLD', 'Escrow hold (locked)'), ('ESCROW_RELEASE', 'Escrow release (to recipient)'), ('ESCROW_REFUND', 'Refund to buyer (internal)'), ('COMMISSION', 'Platform commission'), ('WITHDRAWAL', 'External withdrawal'), ('TRANSFER', 'Internal transfer between wallets'), ('ADJUSTMENT', 'Manual adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.escrowallocation')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.paymenttransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['identifier'], name='wallet_wall_identif_67e4de_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['owner'], name='wallet_wall_owner_i_61f1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['trans_id'], name='wallet_paym_trans_i_c91647_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_type'], name='wallet_paym_transac_72f939_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowallocation',
            index=models.Index(fields=['order_id'], name='wallet_escr_order_i_430d61_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowallocation',
            index=models.Index(fields=['status'], name='wallet_escr_status_ed8fac_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowallocation',
            index=models.Index(fields=['created_at'], name='wallet_escr_created_5a18ed_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledger',
            index=models.Index(fields=['wallet', 'entry_type'], name='wallet_wall_wallet__9f33d6_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledger',
            index=models.Index(fields=['created_at'], name='wallet_wall_created_e837b1_idx'),
        ),
    ]
