# Generated by Django 5.2.8 on 2025-12-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrowallocation',
            options={'ordering': ['-created_at']},
        ),
    ]
