# Generated by Django 5.2.8 on 2025-12-10 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('FEEDBACK', 'General Feedback'), ('COMPLAINT', 'Complaint / Issue')], default='FEEDBACK', max_length=20)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Optional screenshot or proof image', null=True, upload_to='customer_feedback/')),
                ('is_resolved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
