# Generated by Django 5.2.8 on 2025-12-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='escrowallocation',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held'), ('RELEASE_REQUESTED', 'Release Requested'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('REVERSE_REQUESTED', 'Reverse Requested'), ('REVERSED', 'Reversed')], default='HELD', max_length=20),
        ),
    ]
