# Generated by Django 5.2.8 on 2025-12-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_userpin_withdrawalaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpin',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userpin',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
