# Generated by Django 5.2.8 on 2025-12-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_userpin_otp_code_userpin_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], max_length=20)),
                ('provider', models.CharField(choices=[('MPESA', 'M-PESA'), ('BANK', 'Bank')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider_fee', models.DecimalField(decimal_places=2, help_text='Fee charged by provider (e.g. MPESA)', max_digits=14)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Fee charged by platform', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fee_type', 'provider', 'is_active'], name='wallet_feer_fee_typ_a2327c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ledger_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='withdraw_check', max_length=50)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet'], name='wallet_wall_wallet__14e87c_idx'), models.Index(fields=['detected_at'], name='wallet_wall_detecte_8627e2_idx')],
            },
        ),
    ]
