# Generated by Django 5.2.8 on 2026-01-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_mpesacallbacklog_paymenttransaction_transaction_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedMpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender_phone', models.CharField(max_length=20)),
                ('bill_ref', models.CharField(max_length=64)),
                ('error', models.TextField()),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='mpesacallbacklog',
            options={'ordering': ['-received_at']},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='walletreconciliationlog',
            options={'ordering': ['-detected_at']},
        ),
    ]
