# Generated by Django 5.2.8 on 2026-01-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_failedmpesatransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacallbacklog',
            name='error',
            field=models.CharField(blank=True, max_length=364, null=True),
        ),
    ]
