# Generated by Django 5.2.8 on 2026-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_mpesacallbacklog_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowallocation',
            name='product_flow_status',
            field=models.CharField(choices=[('CUSTOMER_PAYED', 'Customer Paid'), ('SENT_TO_COURIER', 'Seller Sent to Parcel Company'), ('RECEIVED_BY_COURIER', 'Parcel Company Received Parcel'), ('DELIVERED_BY_COURIER', 'Parcel Delivered by Parcel Company'), ('CUSTOMER_RECEIVED', 'Customer Received Parcel')], default='CUSTOMER_PAYED', max_length=30),
        ),
    ]
