from decouple import config

MPESA_CONSUMER_KEY = config("MPESA_CONSUMER_KEY", cast=str)
MPESA_CONSUMER_SECRET = config("MPESA_CONSUMER_SECRET", cast=str)
MPESA_SHORTCODE = config("MPESA_SHORTCODE", cast=str)
MPESA_PASSKEY = config("MPESA_PASSKEY", cast=str)
MPESA_INITIATOR_NAME = config("MPESA_INITIATOR_NAME", cast=str)
MPESA_INITIATOR_SECURITY_CREDENTIAL = config(
    "MPESA_INITIATOR_SECURITY_CREDENTIAL", cast=str
)
